blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/abinzhao/code-courses/issues
    about: Please ask questions or start a discussion through an issue.
